version: '3.8'

services:
  database-mysql:
    container_name: database-container
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: ${MYSQL_TIME_ZONE}
    ports:
      - ${DB_PORT}
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_0900_ai_ci'
    networks:
      cruru_network:
        ipv4_address: ${DB_IP_ADDRESS}

  application:
    container_name: app_container
    platform: linux/arm64
    depends_on:
      - database-mysql
    restart: always
    image: ${DOCKER_REPO_NAME}/cruru:dev-latest
    ports:
      - ${SERVER_BINDING_PORT}
      - ${MONITORING_BINDING_PORT}
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DDL_AUTO: ${DDL_AUTO}
      SERVER_PORT: ${SERVER_PORT}
      DOCKER_REPO_NAME: ${DOCKER_REPO_NAME}
      MONITORING_PORT: ${MONITORING_PORT}
      MONITORING_BASE_PATH: ${MONITORING_BASE_PATH}
      APPLY_POST_BASE_URL: ${APPLY_POST_BASE_URL}
      JWT_TOKEN_SECRET_KEY: ${JWT_TOKEN_SECRET_KEY}
      JWT_TOKEN_EXPIRE_CYCLE: ${JWT_TOKEN_EXPIRE_CYCLE}
      JWT_SIGN_ALGORITHM: ${JWT_SIGN_ALGORITHM}
      COOKIE_ACCESS_TOKEN_KEY: ${COOKIE_ACCESS_TOKEN_KEY}
      COOKIE_HTTP_ONLY: ${COOKIE_HTTP_ONLY}
      COOKIE_SECURE: ${COOKIE_SECURE}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      COOKIE_PATH: ${COOKIE_PATH}
      COOKIE_SAME_SITE: ${COOKIE_SAME_SITE}
      COOKIE_MAX_AGE: ${COOKIE_MAX_AGE}
    networks:
      cruru_network:
        ipv4_address: ${APP_IP_ADDRESS}

networks:
  cruru_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
