name: Deploy to Docker

on:
  push:
    branches:
      - main
      - be/develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend      

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract secrets to .env file
      run: |
        echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env

    - name: Build and push Docker image
      run: |
        # ls -al  # 현재 디렉토리 구조 확인
        # pwd  # 현재 경로 확인
        # if [ -d "./backend" ]; then cd backend; else echo "Backend directory not found"; exit 1; fi        
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

    - name: Deploy
      run: |
        # ls -al  # 현재 디렉토리 구조 확인
        # pwd  # 현재 경로 확인
        # if [ -d "./backend" ]; then cd backend; else echo "Backend directory not found"; exit 1; fi
        docker-compose -f docker-compose.yml up -d
